version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: castelo_web
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
